import { RadioStation } from './types';

export const RADIO_STATIONS: RadioStation[] = [
  {
    id: 'hits-fm',
    name: 'Hits FM',
    country: 'ESPAÑA',
    countryCode: 'ES',
    flag: '🇪🇸',
    frequency: 'HIT FM • Los Mejores Éxitos',
    genre: 'POP, DANCE & TOP HITS',
    cover: '/images/radios/hits-fm.svg',
    streamUrl: 'https://bbhitfm.kissfmradio.cires21.com/bbhitfm.mp3',
    accentColor: '#3B82F6',
  },
  {
    id: 'los-40-principales',
    name: 'Los 40 Principales',
    country: 'ESPAÑA',
    countryCode: 'ES',
    flag: '🇪🇸',
    frequency: '93.9 FM • Music Inspires Life',
    genre: 'TOP 40 & POP INTERNACIONAL',
    cover: '/images/radios/los40-principales.png',
    streamUrl: 'https://playerservices.streamtheworld.com/api/livestream-redirect/LOS40AAC.aac?dist=onlineradiobox',
    accentColor: '#F59E0B',
  },
  {
    id: 'los-40-urban',
    name: 'Los 40 Urban',
    country: 'ESPAÑA',
    countryCode: 'ES',
    flag: '🇪🇸',
    frequency: '104.5 FM • El Ritmo de la Calle',
    genre: 'REGGAETÓN, TRAP & URBAN HITS',
    cover: '/images/radios/los40-urban.jpg',
    streamUrl: 'https://playerservices.streamtheworld.com/api/livestream-redirect/LOS40_URBANAAC.aac?dist=onlineradiobox',
    accentColor: '#DE4176',
  },
  {
    id: 'la-mega-979',
    name: 'La Mega 97.9',
    country: 'ESTADOS UNIDOS',
    countryCode: 'US',
    flag: '🇺🇸',
    frequency: '97.9 FM • New York & Miami',
    genre: 'EL VACILÓN DE LA MAÑANA & LATIN HITS',
    cover: '/images/radios/lamega-979.jpg',
    streamUrl: 'https://liveaudio.lamusica.com/NY_WSKQ_icy?aw_0_1st.playerld=onlineradiobox',
    accentColor: '#EF4444',
  },
  {
    id: 'la-nueva-94-fm',
    name: 'La Nueva 94 FM',
    country: 'PUERTO RICO',
    countryCode: 'PR',
    flag: '🇵🇷',
    frequency: '94.7 FM • La Estación del Género',
    genre: 'REGGAETÓN & TRAP BORICUA',
    cover: '/images/radios/lanueva-94.jpg',
    streamUrl: 'https://liveaudio.lamusica.com/PR_WODA_icy?aw_0_1st.playerld=onlineradiobox',
    accentColor: '#8B5CF6',
  },
  {
    id: 'la-mega-colombia',
    name: 'La Mega Colombia',
    country: 'COLOMBIA',
    countryCode: 'CO',
    flag: '🇨🇴',
    frequency: '90.9 FM • Solo Éxitos',
    genre: 'EL CARTEL DE LA MEGA & PERREO',
    cover: '/images/radios/lamega-colombia.jpg',
    streamUrl: 'https://mdstrm.com/audio/632c9ae6660fef03fe3855fe/live.m3u8',
    accentColor: '#F97316',
  },
  {
    id: 'moda-te-mueve',
    name: 'Moda Te Mueve',
    country: 'PERÚ',
    countryCode: 'PE',
    flag: '🇵🇪',
    frequency: '97.3 FM • Lima & Todo el Perú',
    genre: 'REGGAETÓN, LATIN POP & TRAP',
    cover: '/images/radios/moda-temueve.jpg',
    streamUrl: 'https://mdstrm.com/audio/6839e1c82cc4c480fcd318dd/live.m3u8',
    accentColor: '#14B8A6',
  },
  {
    id: 'radiokiss-fm',
    name: 'RadioKiss FM',
    country: 'ESPAÑA',
    countryCode: 'ES',
    flag: '🇪🇸',
    frequency: '102.7 FM • Lo Mejor de los 80, 90 y Hoy',
    genre: 'POP ROCK, RETRO & HITS',
    cover: '/images/radios/kissfm.jpg',
    streamUrl: 'https://bbkissfm.kissfmradio.cires21.com/bbkissfm.mp3',
    accentColor: '#6366F1',
  },
  {
    id: 'cadena-100',
    name: 'Cadena 100',
    country: 'ESPAÑA',
    countryCode: 'ES',
    flag: '🇪🇸',
    frequency: '99.5 FM • La Mejor Variedad Musical',
    genre: 'HAPPY MUSIC & POP ADULTO',
    cover: '/images/radios/cadena100.jpg',
    streamUrl: 'https://cadena100-cope.flumotion.com/playlist.m3u8',
    accentColor: '#0284C7',
  },
  {
    id: 'megastar-fm',
    name: 'MegaStar FM',
    country: 'ESPAÑA',
    countryCode: 'ES',
    flag: '🇪🇸',
    frequency: '100.7 FM • Solo Temazos',
    genre: 'ELECTRO LATINO, EDM & DANCE',
    cover: '/images/radios/megastar.jpg',
    streamUrl: 'https://megastar-cope.flumotion.com/playlist.m3u8',
    accentColor: '#E11D48',
  },
];
